site_name: networking
site_description: Simple app for manage mutual friendship
repo_url: https://github.com/kob22/networking-web
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/kob22">kob22</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
