# Generated by Django 3.1.3 on 2020-11-18 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_friend', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ensure UID is any non-negative integer number')])),
                ('second_friend', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ensure UID is any non-negative integer number')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('first_friend', 'second_friend'), name='Unique Friendship'),
        ),
    ]
