# Generated by Django 3.1.3 on 2020-11-19 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='first_friend',
            field=models.PositiveBigIntegerField(error_messages={'invalid': 'Ensure UID is any non-negative integer number'}, validators=[django.core.validators.MinValueValidator(1, message='Ensure UID is any non-negative integer number')]),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='second_friend',
            field=models.PositiveBigIntegerField(error_messages={'invalid': 'Ensure UID is any non-negative integer number'}, validators=[django.core.validators.MinValueValidator(1, message='Ensure UID is any non-negative integer number')]),
        ),
    ]
